### ISSUE TITLE
include RNA-seq pipeline

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#276]

**Comment by cokelaer** [comment]
TODO list:

- [ ] star: to be tested and included
- [ ] tophat: to be tested and included
- [ ] switch bowtie/star/tophat RL
- [ ] tutorial in the doc  + data set example TC
- [ ] clean_ngs : RL
- [ ] test: full scale analysis: L
- [ ] integration gui   : DD
- [ ] Cleaning step: TC/RL

**Comment by rlegendre** [comment]
take account of paired end data on clean_ngs (TODO)
