### ISSUE TITLE
Variant calling

### ISSUE THREAD

**Issue by ddesvillechabrol** [sequana/sequana#298]
- [ ] add multi-summary in pipeline for easier navigation
- [ ] add vt peek after filter to have ts/tv ratio
- [x] add joint freebayes if you are more than 1 sample to compare
- [x] add AddReadGroup rule
- [x] bam/bai after filter in report directory
- [x] change logs directory for some rules
- [x] histogram before filter
- [x] snpeff redirect output of build
- [x] bcf filter with pysam (10x faster than vcf.Reader)
- [x] fix javascript if there are only 1 columns
- [x] paragraph about coverage

**Comment by cokelaer** [comment]
closed for now. the two remaining issues have been added to https://github.com/sequana/sequana_variant_calling/issues/1
