### ISSUE TITLE
I would like to join

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#306]
Please, let us know if you would like to join the project.

You can contribute in various ways:
- [ ] improving the documentation
- [ ]  add new Python functions / plotting
- [ ] add new pipelines
- [ ] add new docker images
- [ ] add new visualisations
- [ ] add HTML / Javascript functionalities
- [ ]  add bug reports

**Comment by blaiseli** [comment]
Hi, I would like to join the project. I have written some snakemake pipelines, and I will try to see if they can be ported to the sequana infrastructure.

**Comment by cokelaer** [comment]
I've added you. welcome on board.

**Comment by blaiseli** [comment]
To be honest, after having a quick look, it seems much more complicated than I expected. You seem to have implemented various layers of wrapping around snakemake. It looks like it requires quite some effort to become familiar enough with the whole infrastructure to be able to contribute.

I thought sequana was mostly a collection of plain snakemake pipelines or wrappers as described here: https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html

**Comment by cokelaer** [comment]
@blaiseli we can discuss about if off line. In a few words, the wrapping around snakamake itself are actually rather small. We added a couple of functions to help users but they are optional. You can simply add your pipeline in a directory (sequana/pipelines) and that's it. You just need to add a README as explained in the developer guide. I think we enforce the use of a config file though and you must name your pipeline Snakefile.rules. I need to provide a complete documentation on this aspect. 

However, if you want to decompose your pipelines with rules that can be re-used, then you will probably need to make a few updates to your code but then they can be re-used by other pipelines. 

Again, we can discuss about this off-line.
