### ISSUE TITLE
Pb reference option

### ISSUE THREAD

**Issue by chrisBiomics** [sequana/sequana#318]
L'option reference n'est pas fonctionnelle avec le pipeline variant_calling

error message
AttributeError: 'AttrDict' object has no attribute 'bwa_mem'

**Comment by cokelaer** [comment]
Hi Chris, 
What version of Sequana are you using ? Is it the one from pypi website ? or from the source code ?

**Comment by cokelaer** [comment]
Salut Christiane, 
Fixed in the version 0.17.0 and updated on the cluster.
