### ISSUE TITLE
add cluster config ?

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#320]
When I ran star with default parameters I had this issue : 
`slurmstepd: error: Step 7758171.0 exceeded memory limit (5120668 > 5120000), being killed
srun: Exceeded job memory limit
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.`

I know my STAR-job need more RAM (at least 30Go pour a human genome)
If I add a cluster config json file, it's ok : 
`{ 
    "__default__" :
    {
        "ram" : "3G"
    },
	"star_mapping" : 
	{ 
		"ram" : "34G" 
	} 
}`

But for include this config I modify the run.sh with : 
`snakemake -s rnaseq.rules --stats stats.txt -p -j 16 --nolock --cluster-config cluster_config.json --cluster "sbatch --mem={cluster.ram} --qos normal"`

I think we need to discuss about the best way to include cluster parameters by rule in pipelines

**Comment by cokelaer** [comment]
This is implemented in both sequana and sequanix standalones.  would require some testings.

In sequana, if there is a config_cluster in the pipeline, it is copied in the working directory and the runme.sh contains --cluster-config CONFIG .  Same in Sequanix but the file is not copied. Instead, we keep the full path and set it as a snakemake parameter in the snakemake dialog, which can be changed to a local file if needed.
