### ISSUE TITLE
reports should be web independent

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#338]
javscript and css should be part of sequana and no external links included in the HTML pagse; 
This will ensure that HTML reports can be open on a cluster that has no web access

**Comment by cokelaer** [comment]
probably the galleria/jquery dependencies that we can remove. It is used in fastq_stats to have the nice gallery but this is a large dependencies

**Comment by ddesvillechabrol** [comment]
There are no more web dependencies with the new report system.
