### ISSUE TITLE
No NH tag in bowtie output

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#339]
Issue when featureCounts run after bowtie : all reads (unique and multiples) are counted as unique because bowtie don't use NH tag for mark multiple alignments.
Two possibilities : 
- Create a rule HTseq-count
- Create a custom rule after bowtie for adding NH tag (use pysam ?)

**Comment by cokelaer** [comment]
Need to add the tag for each read .

**Comment by rlegendre** [comment]
fixed by using bowtie2
