### ISSUE TITLE
pigz -p issue 

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#364]
When using pigz or unpigz, all arguments must be before the filename. 
This was fixed for compressor but not everywhere.For isntance bwa_bam_to_fastq 
To be corrected in all rules / pipelines

**Comment by cokelaer** [comment]
digital_normalisation/digital_normalisation.rules also
bowtie1_mapping_dynamic.rules
and gz_to_fastq.rules

**Comment by rlegendre** [comment]
issue solved
