### ISSUE TITLE
sequanix improvements

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#398]
- [x] when sequanix progress bar starts it is at 0% and may hang for a while for the first job to finish and see the progress bar to move to 1% This is misleading and gives the impression that nothing is going on

- [x] if there are issues, we may want to save all the logger, snakemake output, slum log into a bundle file
- [x]  fix the expansion of the "running" tabs
- [x] clear the snakemake output
- [x] importting a config before the pipeline (in the main menu) causes a crash

--

**Comment by cokelaer** [comment]
Fit the "importing config" bug

**Comment by rlegendre** [comment]
[ ] Ability to choose a directory (and not a file) with the correct suffix in config.yml ?
