### ISSUE TITLE
Sequanix : No rule to produce adapter_removal 

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#412]
When you choose "until adapter_removal" rule and you click on show dag, you have this error : 

Could not create the DAG file.

b"MissingRuleException:
No rule to produce adapter_removal (if you use input functions make sure that they don't raise unexpected exceptions).
ERROR:snakemake.logging:MissingRuleException:
No rule to produce adapter_removal (if you use input functions make sure that they don't raise unexpected exceptions).
"

===> it's because the rule "removal_adapter" does'nt exist, but the rule "cutadapt" exist !

**Comment by cokelaer** [comment]
Fixed. Replaced adapter_removal with cutadapt where required.
