### ISSUE TITLE
JOSS review: readthedocs.io overview section

### ISSUE THREAD

**Issue by bow** [sequana/sequana#437]
I find that after running `conda install sequana` and running the example [here](http://sequana.readthedocs.io/en/master/userguide.html#sequana-library), I could not reproduce the plot. The standalone example with `sequana_coverage` works fine, though.

1. Is there something that needs to be setup that I may be missing?
2. Have you looked into using an jupyter notebook for this part? Maybe linking into an externally hosted notebook file, with the commands shown, is easier for the user?

(Main review thread: [here](https://github.com/openjournals/joss-reviews/issues/352))

**Comment by cokelaer** [comment]
strange, I just re-did the plot either from the link you posted or using the standalone.

1. the genome coverage code does not rely on specific bioinformatics package. It is a home-made tool based on numpy/pandas/matplotlib only so nothing special to set up 
2. we have a notebook https://github.com/sequana/sequana/blob/master/notebooks/coverage.ipynb I have added a *see also* in the documentation (not yet built) that should appear on the develop branch later.

- [ ] check the notebook link 
- [ ]  I will try the *sequana* version from conda to check whether I can reproduce the script and run the notebook

**Comment by cokelaer** [comment]
The plot [here](http://sequana.readthedocs.io/en/master/userguide.html#example-1-running-median-on-coverage) was sightly different from was you get when copying/pasting the code: the parameter 5001 in the code did not correspond to the picture (where 4001 was used). This is fixed but I am still wondering if that's what you meant by "I could not reproduce the plot". 

I tried with the latest version of sequana on bioconda and using the standalone I got the same correct answer; same using the shell commands. 

the notebook link appears in the "develop" version of the documentation. [here](http://sequana.readthedocs.io/en/develop/userguide.html#sequana-standalones)

**Comment by bow** [comment]
Aha, I've missed the notebook. It is indeed handy to have (especially with the interactive widget).

As for when I mentioned I could not reproduce, I meant I could not create the plots at all. I tried running them inside a notebook (the same environment as the sequana installation), but nothing was shown.

This was a verbatim copy-paste of the commands, though. I think it's the `%pylab inline` directive that needs to be added to my notebook.

I guess the example is also not meant to be run on its own Python script then?

**Comment by cokelaer** [comment]
the example related to the enome coverage can be used inside the notebook (indeed with %pylab inline at the top of the notebook to show the images) or within a Python script. WE have wrap most of the code inside the standalone application sequana_coverage.

**Comment by bow** [comment]
Ok ~ feel free to mark the issue closed. I tried it again (copying verbatim) the notebook you linked and it works ok. Replacing the BED file with the BED file in the current documentation also works.
