### ISSUE TITLE
JOSS review: typos

### ISSUE THREAD

**Issue by bow** [sequana/sequana#440]
These are some collections to typos that I found during the review. I will reply to this thread if I find more. For now here are the list:

* `Since there are part of the Sequana` [docs, section 2.4](https://sequana.readthedocs.io/en/master/userguide.html#sequana-reports)
* `... of New Generation Sequencing (NGS) ` -> I believe it should be `Next Generation ...` [submission paper.md]
* `... which ease the decomposition of pipelines into modular sub-units.` [submission paper.md], should be `... which eases the decomposition of pipelines into modular sub-units.`
* `The reports are used to store the results of a pipelines but also materials required to reprodude the results.` [submission paper.md](https://github.com/sequana/sequana/blob/master/doc/joss/paper.md)
* `analysis tasks (e.g., variant calling filtering)` [submission paper.md], perhaps you meant `(e.g. variant calling)` or `(e.g. variant call filtering)`?
* ` as well as tool to perform` [submission paper.md], should be `as well as a tool to perform`
* ` test suite (on Travis.org) ` [submission paper.md]. The address is travis-ci.org, and this can be made into a hyperlink.
* ` and faster by taking care of the dependencies (e.g., samtools, bwa standalones, or Python librairies).` [submission paper.md], I think `bwa` (without `standalones` is sufficient) and it should be `libraries`.

(Main review thread: [here](https://github.com/openjournals/joss-reviews/issues/352))

**Comment by cokelaer** [comment]
We fixed the typos mentioned here abive. thanks

**Comment by bow** [comment]
Almost there ~ the link to Travis still says `Travis.org` (missing `-ci`) and points to `travis.ci.org` (should be`travis-ci` instead of `travis.ci`) :).

**Comment by cokelaer** [comment]
fixed

**Comment by bow** [comment]
Almost there ~ could you replace the displayed `Travis.org` link to either showing `travis-ci.org` or just `Travis CI`? It does already link to the correct URL, but the displayed text `Travis.org` points to something completely different.
