### ISSUE TITLE
JOSS review: tag release

### ISSUE THREAD

**Issue by bow** [sequana/sequana#441]
This is more of a placeholder issue for after the review is done: a version tag (0.4.1) should be added to the git repository. 

As a side note, it may also be useful to add git tags for previously released versions of sequana. This would show up in the [`releases` section](https://github.com/sequana/sequana/releases) nicely.

(Main review thread: [here](https://github.com/openjournals/joss-reviews/issues/352))

**Comment by cokelaer** [comment]
play, good point. We post releases on pypi in general but not on github but we could do both indeed.

**Comment by bow** [comment]
Yes, this is more of a reproducibility issue for developers intending to play around with a specific release version. Right now, one has to manually trawl the commit messages. With a git tag, one can just checkout the tag and have the exact same state of the code as when it is released for that tag.

**Comment by cokelaer** [comment]
done for 0.4.2

**Comment by bow** [comment]
Great, just #439 remaining then? Otherwise, I think this is ready :).
