### ISSUE TITLE
atac-seq pipeline 

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#443]
todo: 

- [x]  change bowtie2 rule for take account of paired end data
- [ ]  include a design file for MACS2 (not mandatory for ATAC data)
- [x]  include all needed tools from Deeptools
- [ ]  include a plot of Qvalue ?

**Comment by rlegendre** [comment]
Some issues with installing MACS2 and picard-tools:
- MACS2 is written on python 2.7 and not compatible with recent python version. An issue is open in their github : https://github.com/taoliu/MACS/issues/179
- collectInsertSizeMetrics (from picard-tool): need R installed.

**Comment by cokelaer** [comment]
Not relevant anymore
