### ISSUE TITLE
Cutadapt rule: revcomp adapters not taken into account

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#446]
in the command line, the revcomp adapters are not removed from the fastq ! 

```
This is cutadapt 1.14 with Python 3.5.3
Command line parameters: FP-sub16AsR4_GTGAAA_L001_R1_001.rc.fastq.gz -b file:FP-sub16AsR4_GTGAAA_L001/cutadapt/FP-sub16AsR4_adapters_fwd.fa -m 20 -q 30 -O 6 --trim-n -o FP-sub16AsR4_GTGAAA_L001/cutadapt/FP-sub16AsR4_GTGAAA_L001_R1_.cutadapt.fastq.gz
```

**Comment by rlegendre** [comment]
Maybe concatenate the adapter files would be a best idea ? instead of give two adaters files (with fwd and revcomp adapters) for single end data

**Comment by cokelaer** [comment]
@rlegendre  I believe this was not a bug anymore following a discussion a while ago ?

**Comment by cokelaer** [comment]
obsolet
