### ISSUE TITLE
variant calling warning

### ISSUE THREAD

**Issue by lgpf** [sequana/sequana#468]
File path FRC0434_S81/add_read_group//FRC0434_S81.rg.sorted.bam contains double '/'. This is likely unintended.

**Comment by ddesvillechabrol** [comment]
Hello @lgpf ! 

Thanks for the bug report !
I fixed it on the master branch.

Cheers,
Dimitri

**Comment by lgpf** [comment]
Thank you Dimitri!
Really a great work that you've done so far.

Best,
Leonardo.
