### ISSUE TITLE
Error in job RNAseQC

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#489]
> Error in job RNAseQC while creating output files RNAseQC/Transcript-associated_Reads_metrics.svg, RNAseQC, RNAseQC/sample_index.txt.
ERROR:snakemake.logging:Error in job RNAseQC while creating output files RNAseQC/Transcript-associated_Reads_metrics.svg, RNAseQC, RNAseQC/sample_index.txt.
RuleException:
CalledProcessError in line 64 of sequana/sequana/rules/RNAseQC/RNAseQC.rules:
Command 'rna-seqc -o RNAseQC  -r Genomes/hg19/hg19.fa  -s RNAseQC/sample_index.txt -t annotation/gtf/hg19.gtf  -BWArRNA /human_rRNA/human_all_rRNA.fasta  2> RNAseQC/RNAseQC.log' returned non-zero exit status 1
  File "sequana/sequana/rules/RNAseQC/RNAseQC.rules", line 64, in __rule_RNAseQC
  File "conda/envs/py35/lib/python3.5/concurrent/futures/thread.py", line 55, in run

**Comment by rlegendre** [comment]
The bug was corrected but there was still a error with the conda version of RNAseQC. 
So for use RNA-SeQC, we must to use module for load RNA-SeQC before to run the pipeline

**Comment by cokelaer** [comment]
Does it mean that the version on bioconda is not up to date? If so, we/I can update the version on bioconda if required

**Comment by rlegendre** [comment]
Unfortunately, the version on conda doesn't work. I had ask for a update few month ago and the developper said "it work for me"...

**Comment by cokelaer** [comment]
What version do you need?

**Comment by cokelaer** [comment]
What version do you need?

Le 14 déc. 2017 13:10, "rlegendre" <notifications@github.com> a écrit :

Unfortunately, the version on conda doesn't work. I had ask for a update
few month ago and the developper said "it work for me"...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sequana/sequana/issues/489#issuecomment-351693788>, or mute
the thread

**Comment by rlegendre** [comment]
I think there is only one available version : 1.1.8

**Comment by cokelaer** [comment]
But which version do you need?

**Comment by rlegendre** [comment]
version 1.1.8

**Comment by rlegendre** [comment]
see issue in https://github.com/bioconda/bioconda-recipes/issues/4945 for advancements

**Comment by bgruening** [comment]
There is now a new conda package. This should now work. Issue can be closed?

**Comment by cokelaer** [comment]
now available indeed
