### ISSUE TITLE
Improvements in RNAseq pipeline

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#502]
- [ ] Add the gene_length and tsv file creation during the index step
- [ ] All indexes are done when you put 'true' in genome section. Take in into account the "do" in each mapper section.
- [ ] Put second STAR mapping as facultative step and use all samples in order to indexe the new genome
- [ ] Clean the STAR directory after the rule and make tmp directory as temp()
- [ ] Add a "options" in star index to allows a GTF during genome indexing or add option "use_gtf"
- [ ]  remove ribosomal reads before to align against genome of reference
- [x] Add bowtie2 as new mapper
- [ ] get tools version information at the end of the pipeline 
- [ ] Add RseQC tools in pipeline, as infer_experiment, BAM_stat and inner_distance.py
- [ ] Add Salmon

**Comment by cokelaer** [comment]
Deprecated. See rnaseq pipeline. Most features are now included
