### ISSUE TITLE
problem on fastqscren and pipeline dir

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [sequana/sequana#505]
I have started froom the tutorial but I have this error:
```
snakemake -s smallrnaseq.rules --stats stats.txt -p -j 4
NameError in line 14 of /home/maurizio/miniconda2/envs/sequana/lib/python3.6/site-packages/sequana/rules/Taxonomy/fastq_screen_report/fastq_screen_report.rules:
name '__fastq_screen_report__sample' is not defined
  File "/home/maurizio/Desktop/Analisi_mirna_19feb2018/RAW/analysis/smallrnaseq.rules", line 126, in <module>
  File "/home/maurizio/miniconda2/envs/sequana/lib/python3.6/site-packages/sequana/rules/Taxonomy/fastq_screen_report/fastq_screen_report.rules", line 14, in <module>
(sequana) 
```

**Comment by rlegendre** [comment]
Hi bioinfo-dirty-jobs,

This issue was corrected a few week ago, but we have not already update the conda package of sequana.
If you want to use the last version of sequana, you can clone the master repository and run the tutorial again.

Thanks to use Sequana and all my apologizes for this bug.

**Comment by rlegendre** [comment]
Solved in latest version. Please reopen the issue if you have always the bug.
