### ISSUE TITLE
Forcing use of lowercase "star" in aligner choice for rna-seq pipeline

### ISSUE THREAD

**Issue by khourhin** [sequana/sequana#572]
Currently, we can specify either "star" or "STAR" for aligner in the rna-seq pipeline. I think removing the "STAR" possibility, and forcing the use of "star" would simplify latter code. For example see this directly linked bug #571

**Comment by cokelaer** [comment]
Fixed in the rnaseq pipeline itself. (Note for IP users: should be fixed on the cluster as well)
