### ISSUE TITLE
Long Running Process in Sequana/Sequanix

### ISSUE THREAD

**Issue by snunzi** [sequana/sequana#582]
I am successfully running my pipeline with Sequanix, thank you! However, I am running Sequanix on a remote server and connecting with x11. When my connection to the server times out, my running pipeline crashes (The X11 connection broke (error 1). Did the X11 server die?). I have tried running it in screen and with nohup, both with no success, as soon as the GUI closes the pipeline halts. Any advice for launching the Sequana pipeline from the Sequanix GUI and have it continue even after GUI window closes? Some of my pipelines run for a day or more, so I need someway to launch them in the background (easily done outside the GUI, just not sure how to do it within the GUI). 

Thank you!

**Comment by cokelaer** [comment]
@snunzi first of all thanks for using Sequana and Sequanix. 
Sequanix was designed to help us launching pipelines on our clusters. Our main motivation was to help our users to use our pipelines on the cluster indeed. Yet, as you have described in your issue, if the X11 connection broke, then nothing much can be done... It is very useful for short analysis but for long runs closing the X11 closes Sequanix indeed.

Yet, I believe that there are solutions. Maybe you can explore the tools tmux or for X11 the tool xpra (https://askubuntu.com/questions/817082/how-to-keep-a-remote-x11-app-running-after-disconnecting-ssh). I have tried myself, but it looks promising.

**Comment by cokelaer** [comment]
no activities
