### ISSUE TITLE
Error in bowtie2_index.rules

### ISSUE THREAD

**Issue by PierreL-B** [sequana/sequana#596]
# Please fill those information if known:

- sequana version: >= 0.9.3 (latest on 19.04.2021)
- sequana_rnaseq pipeline version 0.13.0

# Description of your problem with error message 

NameError in line 34 of /miniconda3/envs/sequana/lib/python3.7/site-packages/sequana/rules/bowtie2_index/bowtie2_index.rules

Its due to an additionnal underscore in "__bowtie2_index__output_done". When I remove it it works perfectly.

Cheers,
Pierre

**Comment by cokelaer** [comment]
@PierreL-B thanks for the issue. This is corrected in the dev and master branches and pypi as well
