### ISSUE TITLE
ERROR: Cannot uninstall 'ruamel-yaml'.

### ISSUE THREAD

**Issue by Saurias92** [sequana/sequana#748]
# Please fill those information if known:

- sequana version:  sequana_demultiplex-1.2.0

# Description of your problem with error message 

```
ERROR message here: ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed proiect and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
<img width="596" alt="Screenshot 2022-04-21 at 12 08 53" src="https://user-images.githubusercontent.com/66642624/165079598-88ed1bcd-d123-4afb-b1f3-f71823b8a569.png">

# Expected behaviour

# what you think might have happened

**if you think it may be useful, please provide your config.yaml file**

**Comment by cokelaer** [comment]
@Saurias92 @ddesvillechabrol 

Maybe it is a conflict between pip and conda. 

What version of sequana do you use ? How did you install it ? with pip software or conda ? maybe both ?

I know that we may need to update ruamel-yaml with conda sometimes using :

    conda update ruamel_yaml
